### ISSUE TITLE
Check for friendly name edit_finish.jag

### ISSUE THREAD

**Issue by ChamaraPhilipsuom** [wso2-extensions/identity-cloud#3]
https://github.com/wso2-extensions/identity-cloud/blob/5.2.0-M1/jaggeryapps/dashboard/serviceproviders/custom/controllers/custom/edit_finish.jag#L217

 if(conf.inboundAuthType == SAML_SSO){
                samlConfig = conf;
                break;
 }

The inbound config property with name "appType" should be checked whether it is equal to spProperty "appType". In 5.3.0 we can use inboundConfigType for this. 

Same as in "getAppTypeFromAuthnConfigProps" at https://github.com/ChamaraPhilipsuom/identity-inbound-auth-saml-cloud/blob/5.2.0-M1/components/org.wso2.carbon.identity.sso.saml.cloud/src/main/java/org/wso2/carbon/identity/sso/saml/cloud/CloudSAMLSSOService.java#L72

**Comment by madurangasiriwardena** [comment]
Closing the issues since the repo is no longer actively maintained.
